# $FreeBSD$

PORTNAME=	plugins
PORTVERSION=	1.5.3.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Dynamic linking for Haskell and C objects

LICENSE=	BSD

USE_CABAL=	ghc-paths haskell-src random

NO_STAGE=     yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
