# $FreeBSD$

PORTNAME=	network-simple
PORTVERSION=	0.3.0
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple network sockets usage patterns

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	exceptions network transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
