# $FreeBSD$

PORTNAME=	iproute
PORTVERSION=	1.2.11
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	IP Routing Table

LICENSE=	BSD

USE_CABAL=	appar byteorder network

NO_STAGE=     yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
