# $FreeBSD$

PORTNAME=	postgresql-libpq
PORTVERSION=	0.8.2.4
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	low-level binding to libpq

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
