# $FreeBSD$

PORTNAME=	pipes
PORTVERSION=	4.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compositional pipelines

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	mmorph>=1.0.0 mtl>=2.0.1.0 void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
