# $FreeBSD$

PORTNAME=	pipes-network
PORTVERSION=	0.6.0
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use network sockets together with the pipes library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	network network-simple pipes pipes-safe transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
