# $FreeBSD$

PORTNAME=	pipes-safe
PORTVERSION=	2.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Safety for the pipes ecosystem

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	exceptions>=0.3.2 pipes>=4.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
