# $FreeBSD$

PORTNAME=	th-lift
PORTVERSION=	0.5.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Derive Template Haskell's Lift class for datatypes


CABAL_SETUP=	Setup.hs


.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
