# $FreeBSD$

PORTNAME=	hxt-http
PORTVERSION=	9.1.4
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface to native Haskell HTTP package HTTP

LICENSE=	MIT

USE_CABAL=	HTTP>=4000 hxt>=9.1 network>=2.1 parsec>=2.1

NO_STAGE= yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
