# $FreeBSD$

PORTNAME=	hxt-tagsoup
PORTVERSION=	9.1.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	TagSoup parser for HXT


USE_CABAL=	hxt>=9.1 hxt-charproperties>=9 hxt-unicode>=9 tagsoup>=0.13

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
