# $FreeBSD$

PORTNAME=	haskell-src-meta
PORTVERSION=	0.6.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse source to template-haskell abstract syntax

LICENSE=	BSD

USE_CABAL=	haskell-src-exts syb>=0.1 th-orphans>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
