# $FreeBSD$

PORTNAME=	HandsomeSoup
PORTVERSION=	0.3.2
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Work with HTML more easily in HXT

LICENSE=	BSD

USE_CABAL=	HTTP hxt hxt-http MaybeT mtl network parsec transformers

NO_STAGE= yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
