# $FreeBSD$

PORTNAME=	th-orphans
PORTVERSION=	0.7.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Orphan instances for TH datatypes

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	th-lift

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
